### ISSUE TITLE
Feature Request: Scanning bulk quantities of items

### ISSUE THREAD

**Issue by Socapexxx** [CompositeLight/currentRMS-helper#13]
It would be nice to have a way to adjust the quantity in the allocate section, while also scanning the asset, in the same barcode.

Thinking the barcode would have a keyword, followed by quantity, followed by the bulk barcode. The extension would listen for the keyword in the scanned asset, set the quantity field to the amount, then set the asset to the bulk barcode.

Not sure if this is feesable or I should look into using AHK.

An example would be a case of lights, where you might have 2 powercon cables, 2 brackets, 2 safety chains, all bulk items, but with barcodes inside the case. The user can easily count the quantity, but we are finding that sometimes there is user error where they might miss one clamp for example, and we don't know if its actually missing or just an error.

**Comment by Socapexxx** [comment]
That sounds great! love the prefix.

We recently bought a batch of new moving lights, and as you said barcoding everything is the best way to work, so we barcoded the clamps. One out of 24 wasn't scanned on the job, so we were questioning ourselves to whether we actually scanned it, or left it somewhere.....

**Comment by CompositeLight** [comment]
This feature is now added (1.21.0). Thanks for the suggestion. Enjoy!
