### ISSUE TITLE
Feature Request: Add custom actions

### ISSUE THREAD

**Issue by epictechmedia** [CompositeLight/currentRMS-helper#15]
It'd be nice to be able to insert custom actions in the 'Actions' sidebar to open a URL.

Probably be difficult for each opportunity to have a custom URL, but one for something like "Subcontract logistics" and it opens a courier booking form as an example.

If these could be configured in the extension pop-up too, that'd be great but code is probably less faff to begin with.

**Comment by CompositeLight** [comment]
I think for this to have real value versus using normal browser shortcuts / favourites it would need to lift data from Current (like venue) and auto-paste it into the booking for you land on. Nice idea, but difficult to do in any kind of "universal" way.

**Comment by ClearsoundPro** [comment]
If I’m reading this right you can already add a URL into a custom field as a “website” type on a opportunity, this will then pop up on the right hand side as a clickable link.On 10 Jan 2024, at 17:31, EpicTech Media ***@***.***> wrote:﻿
It'd be nice to be able to insert custom actions in the 'Actions' sidebar to open a URL.
Probably be difficult for each opportunity to have a custom URL, but one for something like "Subcontract logistics" and it opens a courier booking form as an example.
If these could be configured in the extension pop-up too, that'd be great but code is probably less faff to begin with.
