### ISSUE TITLE
Feature Request: Allocate tab as default

### ISSUE THREAD

**Issue by Kabukiman1** [CompositeLight/currentRMS-helper#19]
On page load "Function" tab is the default.
Can the "Allocate" tab be the default on page load? 

Thanks!

**Comment by ClearsoundPro** [comment]
This sounds like a great idea, I have thought of this already or at least have the option?

**Comment by Kabukiman1** [comment]
A colleague of mine thought it did already go into the allocate tab as default be was unsure, maybe it as unintentionally changed back with a later update?

Selecting the allocate tab auto selects prepared and puts curser in asset box which is great!

**Comment by CompositeLight** [comment]
The "stock" behaviour is to load to the Functions tab, which does make some sense if you consider that a user might be checking in equipment, or booking it out. Would be possible to make an option to default to Allocate tab, and I think we'd probably use it, so consider it on the list.

**Comment by CompositeLight** [comment]
Closing this one as unplanned. The reason is this: The way audio works in a browser now is that it cannot be played unless there has been at least some interaction with the page by the user. Needing to click on the Allocate tab, whilst otherwise unnecessary, satisfies this requirement - so it's a necessary click.

**Comment by CompositeLight** [comment]
I was wrong about this. Or rather, while it's true that user interaction is required to enable sounds there isn't actually any need for sounds until something has been scanned - which counts as an interaction, and enables sounds.

Added into V1.30.11, settable by the pop-up with default to on.
