### ISSUE TITLE
New Feature: Revert items back to un-allocated state

### ISSUE THREAD

**Issue by CompositeLight** [CompositeLight/currentRMS-helper#2]
The idea is to add an option to the Functions dropdown that would allow you to revert items back to Reserved in a single operation. Currently if the item(s) are Prepared you have to run the revert operation twice to clear them out.

**Comment by CompositeLight** [comment]
Additional: It should be possible to do this via a scan. Ie. you scan a *remove* barcode, and then the item, and it reverts that item off of the opportunity.

**Comment by CompositeLight** [comment]
For now, I've added a *revert* barcode scan operation into v1.30.11.

**Comment by TechJed** [comment]
Sweeeet
