### ISSUE TITLE
Feature Request: in order view, show item available stock levels  per line

### ISSUE THREAD

**Issue by ClearsoundPro** [CompositeLight/currentRMS-helper#20]
Similar to hire-hop, in order view, on each item line, have a column showing item stock levels. I find this incredibly useful when sorting shortages out. Not only do you see the item in ‘red’ when short, but you also know how many by.

**Comment by CompositeLight** [comment]
Good idea, will add this when I can, subject to API limitations.

**Comment by CompositeLight** [comment]
This is now implemented (V1.30.15)
