### ISSUE TITLE
Feature Request: Number of booked out equipment on products page.

### ISSUE THREAD

**Issue by Kabukiman1** [CompositeLight/currentRMS-helper#21]
Would it be possible on the product page for an item (current-rms.com/products/"number") to show the amount of said product out on each job in the "Bookings" section.

This will alleviate the need to open an additional page (availability) to see this information.

I've shown a potential place here highlighted in the red box:
![image](https://github.com/CompositeLight/currentRMS-helper/assets/156780229/b08724c7-e2e0-43dc-b2fd-68c29f750b0d)

**Comment by CompositeLight** [comment]
This is a great idea, would make this page a lot more useful - thanks! I'll look into it.

**Comment by CompositeLight** [comment]
This is now added for testing in 1.31.0.

**Comment by Kabukiman1** [comment]
AMAZING!

**Comment by CompositeLight** [comment]
No reported issues, so committed to main.
