### ISSUE TITLE
Help Wanted: Product Thumbnail query. 

### ISSUE THREAD

**Issue by Kabukiman1** [CompositeLight/currentRMS-helper#23]
When clicking on the magnifying icon for a product that has no image, a generic cardboard box is displayed.
Though when you update the product with an image, this feature still displays the default box and not the new image.

Is there a time period before it shows? 
Can this be forced to show the new image?

Thanks!

**Comment by CompositeLight** [comment]
Any time you make a change to products or stock - adding, writing off, changing image or location - you need to click "Force Refresh" in the extension's settings panel. I'm planning to add a check for updates so this happens automatically, but for now it's a manual thing.
