### ISSUE TITLE
Feature Request: Prevent quarantined items from being allocated

### ISSUE THREAD

**Issue by CompositeLight** [CompositeLight/currentRMS-helper#24]
As requested by JE. It makes absolutely no sense that you can quarantine an item, perhaps for being unsafe to use, but the system will still allow you to allocate it and send it to site. Will look into adding a check at the point of scanning. Will require an additional API call to retrieve active quarantine information.

**Comment by CompositeLight** [comment]
Added to development branch (V1.30.7) for testing.

**Comment by ClearsoundPro** [comment]
Great ideaThis has happened to us many many times, On 24 Jan 2024, at 15:26, Gareth Risdale ***@***.***> wrote:﻿
As requested by JE. It makes absolutely no sense that you can quarantine an item, perhaps for being unsafe to use, but the system will still allow you to allocate it and send it to site. Will look into adding a check at the point of scanning. Will require an additional API call to retrieve active quarantine information.

**Comment by CompositeLight** [comment]
This is now implemented.
