### ISSUE TITLE
Feature Request: Toggle-able audio

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#36]
Would be great if you could turn the audio on or off in the pop up window as we have people who predominantly use current in the office, so don't need the audio most of the time, but occasionally jump in the warehouse so switching it back on is a long process

**Comment by CompositeLight** [comment]
Which sounds are being played in the office? I thought I'd rolled it back to be just the warehouse scanning ones, but that was a while ago!

**Comment by TechJed** [comment]
Some office people will sometimes sort out transfers and will copy assets from one job to another and then paste the asset in to finalise it on the first and allocate to the second

**Comment by CompositeLight** [comment]
Ah of course. You can always hit mute on the computer, but I'll get around to adding a sounds on/off toggle anyway.

**Comment by TechJed** [comment]
Sweet, cheers! In general we are loving the plugin though, has definitely stopped us switching software for the moment, just infuriating that you’re able to fix all of this in your spare time and they can’t even do it when we’re paying them hundreds!
