### ISSUE TITLE
Feature Request: Hide Booked Out

### ISSUE THREAD

**Issue by b0ngw4ter** [CompositeLight/currentRMS-helper#38]
similar to hide prepared, but to see if anything is left behind

**Comment by CompositeLight** [comment]
I might have a look at this, however you can currently just sort by the status column which brings all three non-booked out items to the top. So it becomes a question of whether it's worth adding a button to the gui for a function that already exists...

**Comment by kennioje** [comment]
I do think it is worth it (I was going to make the same feature request), as it would keep the structure of the opportunity, where as sorting by status hides that information.
For example, hiding Prepared and Booked Out, would still show the groups in which the Reserved items are. This can be really important on big jobs where we use groups to indicate what part of a large site items need to go to.

**Comment by CompositeLight** [comment]
Added in 1.31.14.
