### ISSUE TITLE
Feature Request: Clear all dates button

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#39]
Would be great if there was a button on the edit opportunity page to clear all the dates, as if the date moves or something, it takes too long to manually clear all the fields

**Comment by ClearsoundPro** [comment]
Great idea!

**Comment by CompositeLight** [comment]
Good idea. I'm planning to look at the days calculator at some point, so can work this in then.

**Comment by TechJed** [comment]
Sweet

**Comment by CompositeLight** [comment]
Clear dates button added for testing in V1.31.3

**Comment by CompositeLight** [comment]
Merged into main with 1.31.4. Closing for now pending any further feedback / suggestions. Will hopefully sort out the days calculator at some point.
