### ISSUE TITLE
Feature Request: Show assigned resources to services in order view

### ISSUE THREAD

**Issue by ClearsoundPro** [CompositeLight/currentRMS-helper#40]
It would be useful to see what resources are assigned to services in order view, so for example, underneath "Sound Technician" you would see who has been assigned. a bit like the service view. 

when working on lots of shows I will often forget who's on what show and find myself clinking around to see who is booked.

**Comment by TechJed** [comment]
We currently have to put them in the description, but this would make life easier:)

**Comment by CompositeLight** [comment]
This is a great idea, and next on the to-do list when I get a chance to do some more work on it.

**Comment by CompositeLight** [comment]
Added for testing in 1.31.2...

**Comment by CompositeLight** [comment]
Feedback applied for testing in 1.31.3.

**Comment by CompositeLight** [comment]
Merged into main with 1.31.4. Closing for now pending any further feedback / suggestions.
