### ISSUE TITLE
Feature Request: Services to show red until a resource has been assigned

### ISSUE THREAD

**Issue by ClearsoundPro** [CompositeLight/currentRMS-helper#41]
I'm not sure why this isn't a thing already,

 I get round this by having a job booked out for 20 years with a 100 of each services so all services show red until a resource has been assigned, its a good work around but looks messy on the planner

**Comment by CompositeLight** [comment]
Good idea - and nice work around. The only trouble is if I fix this in the extension it still wouldn't show up for anyone not running the extension or working on their phone etc. Agree it makes no sense that this isn't a thing.

**Comment by TechJed** [comment]
I’m looking into compiling this plugin for safari, as I’d love to use it on my phone but cba with installing Kiwi. Got some time coming up this month so will see if I can get it sorted

**Comment by CompositeLight** [comment]
Added for testing in 1.31.2...

**Comment by CompositeLight** [comment]
Merged into main with 1.31.4. Closing for now pending any further feedback / suggestions.
