### ISSUE TITLE
Feature Request: Hide Checked In / Completed

### ISSUE THREAD

**Issue by hwrichardson999** [CompositeLight/currentRMS-helper#43]
Hi,

When we are checking hires back in an option to toggle Hide Checked In/Completed would be useful, just to see Booked Out.

**Comment by CompositeLight** [comment]
Thanks for your suggestion. Enough people are asking about this that I'll probably add it in at some point. Originally we decided it was unnecessary as you can just sort the view by Status and it kind of give you the list of stuff left to find.

**Comment by CompositeLight** [comment]
Added in 1.31.14.
