### ISSUE TITLE
Feature Request: Chrome Web Store distribution

### ISSUE THREAD

**Issue by benjaminbowles** [CompositeLight/currentRMS-helper#48]
It would be great to get auto-updates and wider distribution through the CWS.
Wider deployment for us is an issue with manual updating on all of our client machines.

**Comment by CompositeLight** [comment]
Hi Ben, this is on the to-do list when I get a chance to work it out. In the meantime, we've solved this by creating a Dropbox account that runs on our warehouse machines. The extension lives in a shared Dropbox folder, so if you update one it pushes to all of them - just restart Chrome and it's done. I think it should work fine with any file sharing setup.

Totally understand proper / automatic updates would be preferable! As soon as my real job allows I'll sort it. 

I live in hope that CurrentRMS might just roll this stuff into the actual software so we don't need an extension... Glad you're finding it useful in the meantime.

**Comment by benjaminbowles** [comment]
Great thanks - that's a good idea, we can make that work for now

**Comment by benjaminbowles** [comment]
Just thinking about this again, would you be able to use the Github releases feature so I can keep track of changes in an automated way?

**Comment by CompositeLight** [comment]
I have no idea how the releases feature works, but in principle yeah sure. I'll look into it.

**Comment by CompositeLight** [comment]
Am now using Releases feature.
