### ISSUE TITLE
Feature Request: Disappearing Error Messages

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#50]
Would be great if the red error messages disappeared after a while as when scanning you can end up with a load that you just don't need to see

**Comment by ClearsoundPro** [comment]
Great idea!

**Comment by CompositeLight** [comment]
Good idea. I guess it's fine so long as the warehouse tech is paying attention when the error gets thrown! Would probably add this as an option where you can set the number of seconds you prefer them to hold for. Some messages, like inspection warnings, should probably stay.

**Comment by TechJed** [comment]
We use android scanners so our techs know straight away, and they quickly fill up the small screens. The main ones that need to be made disappearing would be the Failed to allocate asset(s) messages, and the No reserved bulk stock bookings exist..., plus the quarantines one in the plugin as I haven't worked out how to open the interface on the kiwi browser on android

**Comment by TechJed** [comment]
There is one that still sticks around: You must select an asset. Also could we add that the time is in seconds to the page please?

**Comment by CompositeLight** [comment]
Thanks Jed. Sorted in v1.31.8.

**Comment by TechJed** [comment]
The shortage messages don't seem to get caught by the plugin

**Comment by TechJed** [comment]
Would be great if this applied in the serialised cases too
