### ISSUE TITLE
Bug: API login Issue

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#53]
Have had this issue with a couple of macs on the last two dev releases.
<img width="263" alt="Screenshot 2024-07-03 at 12 27 07 pm" src="https://github.com/CompositeLight/currentRMS-helper/assets/23320915/ec240fee-a153-4d39-93df-1580155aedba">

**Comment by CompositeLight** [comment]
That's dull!

From the API documentation:
"401 Unauthorized: Specifically used when authentication is required and has failed or has not been provided."

I use a Mac to write and test the extension, and haven't seen this issue. Can you tell me more about when it happens? Does it happen all the time? Is there anything that triggers it?

**Comment by TechJed** [comment]
Weird, it happened whenever forcing a refresh, after updating. I just made a new API key and this fixed the issue. Potentially too many calls on the old API key?

**Comment by CompositeLight** [comment]
Could be. It's all a bit of an unknown what happens at their end of the API. Sometimes I find the API just stops working and a page refresh fixes it. Glad you've found a fix anyway.
