### ISSUE TITLE
Feature Request: Case Weight Sorting

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#55]
Would be great if the case weights were sorted in alphabetical order as on big jobs we can easily have 50+ containers so finding the right one takes longer than it would if they were alphabetically sorted

**Comment by CompositeLight** [comment]
Good idea. Currently they're just in a random/arbitrary order. Planning to get those case in case weights sorted soon, will work this in then.

**Comment by CompositeLight** [comment]
Cases are now sorted alphanumerically.
