### ISSUE TITLE
Feature Request: Open opportunities in detail view by default (selectable)

### ISSUE THREAD

**Issue by kennioje** [CompositeLight/currentRMS-helper#59]
It would be useful to be able to set opportunities to open in detail view by default. In the warehouse I very rarely want to open in order view, and have to then click into detail view.

This should be on option in the extension settings; probably off by default. This is where the extension has a huge advantage in that these settings can be per-device. Warehouse want to go to Detail by default, people in the office are more likely to go the Order by default.

**Comment by ClearsoundPro** [comment]
I like this idea :)Dan RiddClearsound Productions LtdMobile: 07976 627833Office: 01608 ***@***.***: www.clearsound.co.ukSent from my iPhoneOn 17 Jul 2024, at 09:36, kennioje ***@***.***> wrote:﻿
It would be useful to be able to set opportunities to open in detail view by default. In the warehouse I very rarely want to open in order view, and have to then click into detail view.
This should be on option in the extension settings; probably off by default. This is where the extension has a huge advantage in that these settings can be per-device. Warehouse want to go to Detail by default, people in the office are more likely to go the Order by default.

**Comment by CompositeLight** [comment]
Great suggestion - thank you. I hadn't realised quite how irritating this is until you pointed it out...

However, overriding the default behaviour here would have some technical challenges, and I personally alternate a lot between wanting Order View or Detail View depending on the day.

So as a compromise, I've gone with making the avatar symbol (the circular multi segment thing on the left hand side) a shortcut to Detail View. So you can click on the Opportunity name as normal, to get to Order View, or click on the round icon to jump straight to Detail View.

Available shortly in 1.31.9. Let me know how you get on.
