### ISSUE TITLE
BUG: Blocking quarantined items even if feature is disabled

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#64]
It appears to be blocking quarantined scans even when feature is disabled

**Comment by CompositeLight** [comment]
Interesting. Seems to be working ok for me, but please can you check in System Setup > Product Settings what your Enforce Stock Availability setting is?

![image](https://github.com/user-attachments/assets/d5d3c287-a886-4f2f-89f5-15fc2c19c5cf)

**Comment by TechJed** [comment]
Yep, it's not current's settings as if I do it in safari with no plugin I can allocate the item

**Comment by CompositeLight** [comment]
Got it. Variable is being set as "false" not false, which means it's always true. Will push a fix later on.

**Comment by CompositeLight** [comment]
Pushed a fix for this to the dev branch (1.31.12). Will be added to the main release once other bits are tested. Let me know if you have any more problems - thanks for reporting it.
