### ISSUE TITLE
Change the Freescan voice prompt to match UI

### ISSUE THREAD

**Issue by epictechmedia** [CompositeLight/currentRMS-helper#7]
Change the freescan toggle voice to be "yes" and "no" to match the Current UI.

**Comment by CompositeLight** [comment]
Having worked with this a bit today, in a noisy environment the words "off" and "on" aren't always that clear. The "O" sound is very pronounced in the google voice, which makes them sound similar. Will change to "yes" and "no" in the next version. Open to suggestions if anyone thinks different phrases would be preferable.

**Comment by CompositeLight** [comment]
No one has complained, so calling this permanent. Thanks!
