### ISSUE TITLE
Feature Request: In picker only allow positive quantities 

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#70]
Often will end up accidentally pressing the down arrow rather than the up arrow, and it tries to add -1 of an item to the job. Would be great if it could stop at 0 and not go below that

**Comment by CompositeLight** [comment]
Nice! Another one that should have been there from day 1:
**min="0"**
...A whole 7 characters of code. Won't be as easy to override it after the fact, but should be doable.

**Comment by TechJed** [comment]
Definitely, not sure why you would ever want to add negative quantities of items to a job. Sorry for the dump of suggestions, just been using it and releasing some of this could be fixed!

**Comment by ClearsoundPro** [comment]
Another great idea

**Comment by CompositeLight** [comment]
Never apologise for dumping gold :-)
Added for testing in V1.31.16
