### ISSUE TITLE
Feature Request: Zero-priced items on invoice removal

### ISSUE THREAD

**Issue by benjaminbowles** [CompositeLight/currentRMS-helper#71]
Ability to remove all zero-priced items, and nested items on an invoice whilst it's unissued.

I spend ages doing this every week!

**Comment by CompositeLight** [comment]
Ben, I think this is something you can do already using liquid syntax in the document template. Are you using a custom template already?

**Comment by benjaminbowles** [comment]
This is true, but then I want to sometimes show £0 item lines - such as "PO Number: XYZ", "Payment Terms: ABC"

**Comment by CompositeLight** [comment]
One solution there is to use a conditional that looks for a prefix on the line. So if the line starts with "// " it gets through (and optionally remove the prefix characters to tidy it up). "// PO Number: XYZ" -> "PO Number: XYZ"

**Comment by benjaminbowles** [comment]
> One solution there is to use a conditional that looks for a prefix on the line. So if the line starts with "// " it gets through (and optionally remove the prefix characters to tidy it up). "// PO Number: XYZ" -> "PO Number: XYZ"

Yes that's fair.

**Comment by ClearsoundPro** [comment]
I would ask Chat GTP, it’s sorted out lots of complicated document liquid syntax for me recently, even making me a shortages list in alphabetical order :~}On 17 Sep 2024, at 22:13, Gareth Risdale ***@***.***> wrote:﻿
Going to close this as I think you're best off pursuing these liquid syntax approaches than me trying to fudge it with javascript. Hope you get it sorted - normally these involve a few hours of swearing at the documentation, but pays off in the end. Good luck!
