### ISSUE TITLE
Bug: Hardcoded subdomain

### ISSUE THREAD

**Issue by kennioje** [CompositeLight/currentRMS-helper#77]
The subdomain `amps.current-rms.com` is hardcoded into line 676 of service-worker.js (v1.31.17) and throwing an error in Edge.
`Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.`

I suspect you don't want that in there!

**Comment by CompositeLight** [comment]
Thanks! It was a note to self whilst coding I think. Have deleted it for the next version.
