### ISSUE TITLE
Hover for Profit on Charge Detail within Order View

### ISSUE THREAD

**Issue by hwrichardson999** [CompositeLight/currentRMS-helper#80]
Hi,

Since the latest update the hover for profit on charge detail within the order view screen doesn't seem to be working.

**Comment by CompositeLight** [comment]
Seems to be working ok for me. Recommend you restart Chrome after updating. Other than that, if you go to Manage Extensions have a look at the extension panel and see if any errors are showing - might help me track it down.

Sometimes the API calls fail - I don't know why, could be many reasons their end of the API - and refreshing the page sorts it out.

**Comment by hwrichardson999** [comment]
No errors are showing but no it's stopped doing it for some reason!
