### ISSUE TITLE
Bug: v1.31.22 Functions>Actions do not work

### ISSUE THREAD

**Issue by kennioje** [CompositeLight/currentRMS-helper#84]
In version 1.31.22 using the tick boxes and then Functions>Action>Prepare, Revert status, etc. does not work.

**Comment by CompositeLight** [comment]
Yes - some kind of screw up somewhere. Struggling to work it out currently. Recommend avoiding v22 for the time being.

**Comment by CompositeLight** [comment]
Sorry this was marked closed prematurely. Hopefully fixed in 1.31.23, currently on Dev branch.
