### ISSUE TITLE
Bug: V1.31.22 doesn't allow selection

### ISSUE THREAD

**Issue by TechJed** [CompositeLight/currentRMS-helper#87]
With V1.31.22 the item selection is now broken

**Comment by kennioje** [comment]
See [ Bug: v1.31.22 Functions>Actions do not work #84 ](https://github.com/CompositeLight/currentRMS-helper/issues/84)
From the reply and that it has been closed, I presume that a fix has been implemented in an as yet unreleased development build.

**Comment by TechJed** [comment]
Ahh my bad, thought I had seen someone mention it but as nothing was open I just thought that was my tired brain!

**Comment by CompositeLight** [comment]
Hopefully fixed in 1.31.23, currently on Dev branch.
